# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct FollowedTagsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `FollowedTagsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ FollowedTagsApi }) = "https://dev.to/api"

const _returntypes_get_followed_tags_FollowedTagsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{FollowedTag},
    Regex("^" * replace("401", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_get_followed_tags(_api::FollowedTagsApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_followed_tags_FollowedTagsApi, "/follows/tags", ["api-key", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Followed Tags

This endpoint allows the client to retrieve a list of the tags they follow.

Params:

Return: Vector{FollowedTag}, OpenAPI.Clients.ApiResponse
"""
function get_followed_tags(_api::FollowedTagsApi; _mediaType=nothing)
    _ctx = _oacinternal_get_followed_tags(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_followed_tags(_api::FollowedTagsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_get_followed_tags(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export get_followed_tags
