# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ReadinglistApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ReadinglistApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ReadinglistApi }) = "https://dev.to/api"

const _returntypes_get_readinglist_ReadinglistApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{ArticleIndex},
    Regex("^" * replace("401", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_get_readinglist(_api::ReadinglistApi; page=nothing, per_page=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "get_readinglist", :minimum, page, 1, false)

    OpenAPI.validate_param("per_page", "get_readinglist", :maximum, per_page, 1000, false)
    OpenAPI.validate_param("per_page", "get_readinglist", :minimum, per_page, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_readinglist_ReadinglistApi, "/readinglist", ["api-key", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "per_page", per_page)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Readinglist

This endpoint allows the client to retrieve a list of articles that were saved to a Users readinglist.         It supports pagination, each page will contain `30` articles by default

Params:
- page::Int64
- per_page::Int64

Return: Vector{ArticleIndex}, OpenAPI.Clients.ApiResponse
"""
function get_readinglist(_api::ReadinglistApi; page=nothing, per_page=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_readinglist(_api; page=page, per_page=per_page, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_readinglist(_api::ReadinglistApi, response_stream::Channel; page=nothing, per_page=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_readinglist(_api; page=page, per_page=per_page, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export get_readinglist
