# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UserInviteParam
User invite parameters

    UserInviteParam(;
        email=nothing,
        name=nothing,
    )

    - email::String
    - name::String
"""
Base.@kwdef mutable struct UserInviteParam <: OpenAPI.APIModel
    email::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function UserInviteParam(email, name, )
        OpenAPI.validate_property(UserInviteParam, Symbol("email"), email)
        OpenAPI.validate_property(UserInviteParam, Symbol("name"), name)
        return new(email, name, )
    end
end # type UserInviteParam

const _property_types_UserInviteParam = Dict{Symbol,String}(Symbol("email")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ UserInviteParam }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserInviteParam[name]))}

function check_required(o::UserInviteParam)
    true
end

function OpenAPI.validate_property(::Type{ UserInviteParam }, name::Symbol, val)
end
