# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Article
Representation of an Article to be created/updated

    Article(;
        article=nothing,
    )

    - article::ArticleArticle
"""
Base.@kwdef mutable struct Article <: OpenAPI.APIModel
    article = nothing # spec type: Union{ Nothing, ArticleArticle }

    function Article(article, )
        OpenAPI.validate_property(Article, Symbol("article"), article)
        return new(article, )
    end
end # type Article

const _property_types_Article = Dict{Symbol,String}(Symbol("article")=>"ArticleArticle", )
OpenAPI.property_type(::Type{ Article }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Article[name]))}

function check_required(o::Article)
    true
end

function OpenAPI.validate_property(::Type{ Article }, name::Symbol, val)
end
