# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VideoArticle_user
Author of the article

    VideoArticleUser(;
        name=nothing,
    )

    - name::String
"""
Base.@kwdef mutable struct VideoArticleUser <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing

    function VideoArticleUser(name, )
        OpenAPI.validate_property(VideoArticleUser, Symbol("name"), name)
        return new(name, )
    end
end # type VideoArticleUser

const _property_types_VideoArticleUser = Dict{Symbol,String}(Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ VideoArticleUser }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VideoArticleUser[name]))}

function check_required(o::VideoArticleUser)
    true
end

function OpenAPI.validate_property(::Type{ VideoArticleUser }, name::Symbol, val)
end
