# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Tag
Representation of a tag

    Tag(;
        id=nothing,
        name=nothing,
        bg_color_hex=nothing,
        text_color_hex=nothing,
    )

    - id::Int64 : Tag id
    - name::String
    - bg_color_hex::String
    - text_color_hex::String
"""
Base.@kwdef mutable struct Tag <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    bg_color_hex::Union{Nothing, String} = nothing
    text_color_hex::Union{Nothing, String} = nothing

    function Tag(id, name, bg_color_hex, text_color_hex, )
        OpenAPI.validate_property(Tag, Symbol("id"), id)
        OpenAPI.validate_property(Tag, Symbol("name"), name)
        OpenAPI.validate_property(Tag, Symbol("bg_color_hex"), bg_color_hex)
        OpenAPI.validate_property(Tag, Symbol("text_color_hex"), text_color_hex)
        return new(id, name, bg_color_hex, text_color_hex, )
    end
end # type Tag

const _property_types_Tag = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("bg_color_hex")=>"String", Symbol("text_color_hex")=>"String", )
OpenAPI.property_type(::Type{ Tag }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Tag[name]))}

function check_required(o::Tag)
    true
end

function OpenAPI.validate_property(::Type{ Tag }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "Tag", :format, val, "int64")
    end
end
